mysite/encuestas/urls.py
from django.urls import path

from . import views	# importar vistas de la app

app_name = 'encuestas'

#	-- URLS PARA VISTAS GENÉRICAS --
urlpatterns = [
	path('', views.portal, name = 'portal'), 	# esto debería estar en la app de login, pero no tengo
	path('portal/', views.portal, name = 'portal'), # esto debería estar en la app de login, pero no tengo
	path('encuestas/',  views.IndexView.as_view(), name = 'encuestas'),
	path('encuestas/pregunta_agregar/', views.AgregarPreguntaView.as_view(), name = 'pregunta_agregar'), # agregado como mejora de Django Tutorial
	path('encuestas/<int:pk>/', views.DetailView.as_view(), name = 'detalles'),
	path('encuestas/<int:pk>/eleccion_agregar/', views.AgregarEleccionView.as_view(), name = 'eleccion_agregar'), # agregado como mejora de Django Tutorial
	path('encuestas/<int:pk>/resultados/', views.ResultsView.as_view(), name = 'resultados'),
	path('encuestas/<int:id_pregunta>/votar/', views.votar, name = 'votar'), # esta de momento no es genérica porque no es similar
]



'''#	-- URLS PARA VISTAS NO GENÉRICAS --
urlpatterns = [
	path('', views.portal, name = 'portal'), 	# esto debería estar en la app de login, pero no tengo
	path('portal/', views.portal, name = 'portal'), # esto debería estar en la app de login, pero no tengo
	path('encuestas/', views.encuestas, name = 'encuestas'),
	path('encuestas/<int:id_pregunta>/', views.detalles, name = 'detalles'),
	path('encuestas/<int:id_pregunta>/resultados/', views.resultados, name = 'resultados'),
	path('encuestas/<int:id_pregunta>/votar/', views.votar, name = 'votar'),
]
'''

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'mysite'
urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('encuestas.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/encuestas/models.py
import datetime

from django.db import models

from django.utils import timezone

from django.contrib import admin

# Create your models here.

class Pregunta(models.Model):
	texto = models.CharField(max_length = 200)
	fec_pub = models.DateTimeField('Fecha de publicación')

	def __str__(self):
		return self.texto

	@admin.display(
		boolean = True,
		description = 'Publicado recientemente'
	)
	def esReciente(self):
		return timezone.now() >= self.fec_pub >= (timezone.now() - datetime.timedelta(days=1))

	class Meta:
		ordering = ['-fec_pub']


class Eleccion(models.Model):
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
	texto = models.CharField(max_length = 200)
	votos = models.IntegerField(default = 0)

	def __str__(self):
		return self.texto

mysite/encuestas/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse, reverse_lazy

from encuestas.models import Pregunta, Eleccion

from django.db.models import F

from django.views import generic

from django.conf import settings

from django.utils import timezone

# Create your views here.
#	-- VISTAS GENÉRICAS --
def portal(request):
	ultimas_cinco_preguntas = Pregunta.objects.order_by('-fec_pub')[:5]
	context = {'ultimas_cinco_preguntas': ultimas_cinco_preguntas, 'titulo': 'Inicio del sitio', 'app_name': 'portal'}
	return render(request, 'encuestas/portal.html', context)

class IndexView(generic.ListView):
#	template_name = 'encuestas/genericas/index_app.html'
	context_object_name = 'lista'

	template_name = 'encuestas/genericas/index_app.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		if self.request.path == reverse('encuestas:encuestas'):
#			context['lista'] = Pregunta.objects.all()
			context['titulo'] = 'Encuestas'

		return context

	def get_queryset(self):
		return Pregunta.objects.filter(fec_pub__lte=timezone.now()).order_by('-fec_pub')[:5]

class DetailView(generic.DetailView):
	model = Pregunta
	template_name = 'encuestas/genericas/detalles.html'
	context_object_name = 'pregunta'

	def get_queryset(self):
		return Pregunta.objects.filter(fec_pub__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Pregunta
	template_name = 'encuestas/genericas/resultados.html'

# agregado como mejora de Django Tutorial
class AgregarPreguntaView(generic.CreateView):
	model = Pregunta
	fields = ['texto', 'fec_pub']
	template_name_suffix = '_agregar'
	template_name = 'encuestas/genericas/pregunta_agregar.html'

	def get_success_url(self):
        	return reverse('encuestas:encuestas', kwargs={})

	def post(self, request, *args, **kwargs):
		pregunta = Pregunta(texto = request.POST.get("texto"), fec_pub = request.POST.get("fec_pub"))
		pregunta.save()
		pregunta.eleccion_set.create(texto = request.POST.get("texto_eleccion1"), votos = 0)
		pregunta.eleccion_set.create(texto = request.POST.get("texto_eleccion2"), votos = 0)
		pregunta.eleccion_set.create(texto = request.POST.get("texto_eleccion3"), votos = 0)
		return HttpResponseRedirect(reverse_lazy('encuestas:encuestas'))

# agregado como mejora de Django Tutorial
class AgregarEleccionView(generic.CreateView):
	model = Eleccion
	fields = ['texto', 'votos']
	template_name_suffix = '_agregar'
	template_name = 'encuestas/genericas/eleccion_agregar.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['pregunta'] = Pregunta.objects.get(pk = self.kwargs['pk'])
		return context

	def get_success_url(self):
		return reverse('encuestas:detalles', self.kwargs.get('pk'))

	def post(self, request, *args, **kwargs):
		pregunta = Pregunta.objects.get(pk = self.kwargs.get('pk'))
		pregunta.eleccion_set.create(texto = request.POST.get("texto"), votos = request.POST.get("votos"))
		pregunta.save()
#		return HttpResponseRedirect(reverse('encuestas:detalles', args=[pregunta.pk]))
#		return HttpResponseRedirect(reverse('encuestas:detalles', kargs={'id_pregunta': pregunta.pk}))
#		return HttpResponseRedirect(reverse('encuestas:detalles', args=[self.pk]))
		return HttpResponseRedirect(reverse('encuestas:detalles', args=(self.kwargs.get('pk'),)))
#		return HttpResponseRedirect(reverse('encuestas:detalles', args=[str(self.pk)]))'''

def votar(request, id_pregunta):
	pregunta = get_object_or_404(Pregunta, pk = id_pregunta)

	try:
		selected_eleccion = pregunta.eleccion_set.get(pk = request.POST['eleccion'])
	except (KeyError, Eleccion.DoesNotExist):
		# volver a mostrar el formulario de la pregunta
		return render(request, 'encuestas/detalles.html', {'pregunta': pregunta, 'msg_err': "No has seleccionado ninguna opción"})
	else:
		selected_eleccion.votos = F('votos') + 1
		selected_eleccion.save()
		return HttpResponseRedirect(reverse('encuestas:resultados', args=(pregunta.id,)))

#	return HttpResponse("Estás votando para la pregunta " + str(id_pregunta))

'''#	-- VISTAS NO GENÉRICAS --
def portal(request):
	ultimas_cinco_preguntas = Pregunta.objects.order_by('-fec_pub')[:5]
	context = {'ultimas_cinco_preguntas': ultimas_cinco_preguntas}
	return render(request, 'encuestas/portal.html', context)

	# hardcoded desde aquí
	output = "<h1>Inicio del sitio</h1><br><br>"
	output += "Estas son las cinco últimas preguntas:<br>"

	ultimas_cinco_preguntas = Pregunta.objects.order_by('-fec_pub')[:5]
	for p in ultimas_cinco_preguntas:
		output += "· " + p.texto + "<br>"

	return HttpResponse(output)
	# hardcoded hasta aquí

def encuestas(request):
	ultimas_cinco_preguntas = Pregunta.objects.order_by('-fec_pub')[:5]
	context = {'ultimas_cinco_preguntas': ultimas_cinco_preguntas}
	return render(request, 'encuestas/inicio.html', context)
#	return HttpResponse("Inicio de encuestas")

def detalles(request, id_pregunta):
	pregunta = get_object_or_404(Pregunta, pk = id_pregunta)
	return render(request, 'encuestas/detalles.html', {'pregunta': pregunta})
	#return HttpResponse("Detalles de pregunta " + str(id_pregunta))

def resultados(request, id_pregunta):
	pregunta = get_object_or_404(Pregunta, pk=id_pregunta)
	return render(request, 'encuestas/resultados.html', {'pregunta': pregunta})
#	return HttpResponse("Resultados de pregunta " + str(id_pregunta))

def votar(request, id_pregunta):
	pregunta = get_object_or_404(Pregunta, pk = id_pregunta)

	try:
		selected_eleccion = pregunta.eleccion_set.get(pk = request.POST['eleccion'])
	except (KeyError, Eleccion.DoesNotExist):
		# volver a mostrar el formulario de la pregunta
		return render(request, 'encuestas/detalles.html', {'pregunta': pregunta, 'msg_err': "No has seleccionado ninguna opción"})
	else:
		selected_eleccion.votos = F('votos') + 1
		selected_eleccion.save()
		return HttpResponseRedirect(reverse('encuestas:resultados', args=(pregunta.id,)))

#	return HttpResponse("Estás votando para la pregunta " + str(id_pregunta))
'''

mysite/encuestas/templates/encuestas/genericas/detalles.html
<a href="{% url 'encuestas:encuestas' %}">volver a 'Encuestas'</a><br><br>
<a href="{% url 'encuestas:resultados' pregunta.id %}">resultados</a><br><br>
<a href="{% url 'encuestas:eleccion_agregar' pregunta.id %}">agregar elecci&oacute;n</a><br><br>
<!--
<h1>Pregunta '{{ pregunta.texto }}'</h1>

<h3>Respuestas:</h3>

<ul>
	{% for eleccion in pregunta.eleccion_set.all %}
	 <li>{{ eleccion.texto }}</li>
	{% endfor %}
</ul>
-->

<form action = "{% url 'encuestas:votar' pregunta.id %}" method="post">
{% csrf_token %}
<fieldset>
	<legend><h1>{{ pregunta.texto }}</h1></legend>
	{% if msg_err %}
	<p><strong>{{ msg_err }}</strong></p>
	{% endif %}

	{% for eleccion in pregunta.eleccion_set.all %}
	<input type="radio" name="eleccion" id="eleccion{{ forloop.counter }}" value="{{ eleccion.id }}">
	<label for="eleccion" id="eleccion{{ forloop.counter }}">{{ eleccion.texto }}</label><br>
	{% endfor %}
</fieldset>
<input type="submit" value="Votar"/>
</form>

mysite/encuestas/templates/encuestas/genericas/eleccion_agregar.html
<html>
	<head>
		<title>Agregar elección a pregunta</title>
	</head>

	<body>
		<p><a href = "{% url 'encuestas:detalles' pregunta.id %}">volver a la pregunta</a></p>

		<h3>Datos de pregunta</h3>
		<label>&nbsp;&nbsp;&nbsp;&nbsp;Texto: '{{ pregunta.texto }}'</label>
		<br><br>
		<label>&nbsp;&nbsp;&nbsp;&nbsp;Fecha de publicaci&oacute;n: '{{ pregunta.fec_pub }}'</label>
		<hr>
		<h3>Datos de nueva elección</h3>
		<form method = "post">{% csrf_token %}
			<label for = "texto">&nbsp;&nbsp;&nbsp;&nbsp;Texto</label>
			<input type = "text" name = "texto">
			<br><br>
			<label for = "votos">&nbsp;&nbsp;&nbsp;&nbsp;Votos</label>
			<input type = "number" name = "votos">

			<br><br><br><br>
			<input type = "submit" value = "Agregar elecci&oacute;n a '{{ pregunta.texto }}'">
		</form>
	</body>
</html>

mysite/encuestas/templates/encuestas/genericas/index_app.html
{% load static %}

<link rel="stylesheet" type"text/css" href="{% static 'encuestas/style.css' %}">

<h1>{{ titulo }}</h1>
<!-- añadido como mejora de Django Tutorial -->
<p>&nbsp &nbsp &nbsp <a href = "{% url 'encuestas:pregunta_agregar' %}">Agregar pregunta</a></p>

{% if lista %}
	<ul>
		{% for e in lista %}
			<li><a href="{% url 'encuestas:detalles' e.id %}">{{ e.texto }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>La lista está vacía</p>
{% endif %}

mysite/encuestas/templates/encuestas/genericas/inicio_sitio.html
<h1>App 'Encuetas'</h1>



{% if lista %}
	<ul>
		{% for app in lista %}
		<li><a href="{% url 'app.name:app' %}">{{ app.name }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>Lista no válida</p>
	<li><a href="{% url 'encuestas:encuestas' %}">Encuestas</a></li>
{% endif %}

mysite/encuestas/templates/encuestas/genericas/pregunta_agregar.html
<html>
	<head>
		<title>Agregar Pregunta</title>
	</head>

	<body>
		<p><a href="{% url 'encuestas:encuestas' %}">volver a 'Encuestas'</a></p>

		<form method = "post">{% csrf_token %}
			<h3>Datos de pregunta</h3>
			{{ form.as_p }}
			<hr>
			<h3>Elecciones</h3>
			<label for = "texto_eleccion1">Texto elección 1</label>
			<input type = "text" name = "texto_eleccion1">
			<br><br>
			
			<label for = "texto_eleccion2">Texto elección 2</label>
			<input type = "text" name = "texto_eleccion2">
			<br><br>
			
			<label for = "texto_eleccion3">Texto elección 3</label>
			<input type = "text" name = "texto_eleccion3">
			<br><br>

			<br><br><br>
			<input type = "submit" value = "Guardar nueva pregunta">
		</form>
	</body>
</html>

mysite/encuestas/templates/encuestas/genericas/resultados.html
<p><a href="{% url 'encuestas:encuestas' %}">volver a 'Encuestas'</a></p>
<!--
<h1>Pregunta '{{ pregunta.texto }}'</h1>

<h3>Respuestas:</h3>

<ul>
	{% for eleccion in pregunta.eleccion_set.all %}
	 <li>{{ eleccion.texto }}</li>
	{% endfor %}
</ul>
-->

<h1>{{ pregunta.texto }}</h1>

<ul>
	{% for eleccion in pregunta.eleccion_set.all %}
	<li>{{ eleccion.texto }} -- {{ eleccion.votos }} voto{{ eleccion.votos | pluralize }}</li>
	{% endfor %}
</ul>

<a href="{% url 'encuestas:detalles' pregunta.id %}">¿Votar de nuevo?</a>

mysite/encuestas/templates/encuestas/inicio.html
<h1>App 'Encuetas'</h1>



{% if ultimas_cinco_preguntas %}
	<ul>
		{% for p in ultimas_cinco_preguntas %}
		<li><a href="{% url 'encuestas:detalles' p.id %}">{{ p.texto }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No hay encuestas disponibles</p>
{% endif %}

mysite/encuestas/templates/encuestas/portal.html
<h1>Inicio del sitio</h1>

<h3>Apps</h3>
<ul>
	<li><a href="{% url 'encuestas:encuestas' %}">Encuestas</a></li>
</ul>